### ISSUE TITLE
history vs trends

### ISSUE THREAD

**Issue by kohonen** [jojohappy/zabbix-relay#1]
it seems that the history/trends option is not working properly. i am exporting zabbix data to elasticearch and when using the "-t history" switch, all items in elasticsearch have an even hour timestamp like it is for trends (20:00:00.000,     21:00:00.000,     22:00:00.000 etc). so i am assuming it ignores the "-t history" switch?

```
# NODE_ENV=production nodejs server.js command -d 'elastic' -g "Application servers" -p '2016-05-18|2016-05-20' -t "history" -u '10.10.10.10:9200'
app02 is over
app01 is over
```
for example cpu user time, which is being polled every 60 seconds:

```
@timestamp 		May 19th 2016, 22:00:00.000
t_id 		ea140gsjdio750deca487c3abf6d548329dd5
t_index 		zabbix.archive-2016.05.19
#_score 		
t_type 		zabbix.archive
tapp 		CPU
#avg 		0.028
thost 		app01
titem 		CPU user time
tkey 		system.cpu.util[,user]
#max 		0.05
#min 		0.021
```

and next ones are:
@timestamp 		May 19th 2016, 21:00:00.000
@timestamp 		May 19th 2016, 20:00:00.000
etc...

**Comment by kohonen** [comment]
i think i found the problem, there is a typo in lib/relay.js, line 45
should be
            histype: result.histype,
instead of 
            histypet: result.histype,

**Comment by jojohappy** [comment]
Oops... I made a mistake and had not make a test, I will fix the bug and write the test soon.
