### ISSUE TITLE
Automated Exports

### ISSUE THREAD

**Issue by kisienya** [jojohappy/zabbix-relay#2]
Hi,

Thanks for this tool.

If I needed to do automated transfers from MySQL to InfluxDB I would probably need a cron job that exports newly created data every 5 minutes or so.

How do I use the -- period flag to specify this?

Cheers

**Comment by jojohappy** [comment]
Thank you for your issue. 

The flag period only support date accurate to day. So if you want to export data within one day, you can submit a PR or use another way to do that now.

I will acknowledge and implement this feature soon.

**Comment by kisienya** [comment]
Thank you for your prompt response.

Waiting to hear from you regarding the implementation of the feature

Blessings

**Comment by jojohappy** [comment]
Now this feature has been come true. You can try it.

**Comment by kisienya** [comment]
Many thanks I will try it out...
