### ISSUE TITLE
cannot import data less than 2h to influx

### ISSUE THREAD

**Issue by kisienya** [jojohappy/zabbix-relay#8]
Hi, 

Thanks again for this tool.

I have been testing this tool. I have been able to import data to influx however when I try to import data less than 2h the application says 
'relay completed' yet there is no data imported.

Kindly help

**Comment by jojohappy** [comment]
Thank you for your response

I will do some testing that can help us to resolve this problem.

**Comment by kisienya** [comment]
Many thanks for the help I will be awaiting your response.

**Comment by kisienya** [comment]
To be more precise look at the query below which yields data with one hour apart. I cannot get data in between the hours

>select max from CPU where item_name='CPU\\ iowait\\ time';
name: CPU
time			max
----			---
1483628400000000000	6.3017
1483632000000000000	4.3124
1483635600000000000	5.996
1483639200000000000	3.1284
1483642800000000000	4.636
1483646400000000000	4.5457
1483650000000000000	4.0155
1483653600000000000	3.124
1483657200000000000	3.7341
1483660800000000000	3.8281
1483664400000000000	4.2965
1483668000000000000	3.1976
1483671600000000000	3.7959
1483675200000000000	4.1597
1483678800000000000	3.1855
1483682400000000000	3.3332
1483686000000000000	2.749
1483689600000000000	4.1541
1483693200000000000	4.6248
1483696800000000000	5.1252
1483700400000000000	5.3737
1483704000000000000	5.0463
1483707600000000000	3.1934

**Comment by kisienya** [comment]
Issue solved it was errors resulting from options I had selected
